### PR TITLE
Fix indentation typo

### PR DESCRIPTION
**Pull request by davidcavazos**
Fix indentation typo in dependabot.yaml file.

R: @aaltay, @brucearctor 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] I agree that my contributions are licensed with both [Apache ASL2](../../LICENSE-APACHE) and [MIT](../../LICENSE-MIT).
 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [`CONTRIBUTING.md`](../../CONTRIBUTING.md) guide for more information.

### CODE REVIEW

**Comment by brucearctor** [comment]
@davidcavazos - is it overkill [ it *might* be, but ?? ] to think we would want to have something that tests line/formatting?  Thoughts?  Generally, I think to introduce tests once I have to go back and correct something that a test can detect.

**Comment by brucearctor** [comment]
happy to approve as is, but ... worth at least consideration/mention/discussion [ and I wonder whether there is a well followed approach here, given how prolific dependabot is.  If there isn't established solution(s), then it absolutely would be overkill to implement one for this ].

**Comment by davidcavazos** [comment]
Yeah, I agree with having these kinds of tests. Unfortunately, there is no longer a way to validate dependabot files locally. They might be working on it, but from what I read the validation is deeply rooted in GitHub itself, and I wonder why it doesn't run the validation test if it detects the config file changed. From my research I couldn't find a way to validate it locally, but I also don't expect that file to change too much in the future unless reviewers change.

**Comment by brucearctor** [comment]
Agreed [ since not likely to change much, and this is also not as critical of a path -- if dependabot breaks, we *should* notice and eventually fix ].

I had imagined as part of CI.  Detecting before merge is the important part, local is nice but in GH is also OK.  I don't have the time to dig into this right now https://github.com/marocchino/validate-dependabot ... but the 30 seconds I spent searching and reading the README sounds like it could protect and ensure remains valid.  Also hasn't been touched for a year, so might not still be good [ and also could not be well supported, leaving us in a pickle if we add to this repo's dependencies and then start using new depandabot features that aren't supported in the validator ].  So, lots of text in this paragraph that you don't need to do anything with :-)

**Comment by aaltay** [comment]
@damccorm - adding you here for the question of: best practices for testing bot configs.

**Comment by damccorm** [comment]
I don't have much to add beyond the conversation above - there's not really an established best practice here, other than maybe merging the changes to your fork and validating things are working there before merging upstream (which is highly manual).

I wouldn't mind trying the validate-dependabot action; its not huge, but it does at least have 30 users - https://github.com/marocchino/validate-dependabot/network/dependents - and its easy to disable if things go badly. Another alternative is yaml linting - https://github.com/ibiqlik/action-yamllint - which would've caught this but won't catch everything. Neither of those options actually test that you've specified your desired behavior, just that your syntax is valid.

Overall, though, my recommendation would probably just be to do nothing. The cost of messing up one of these configs is pretty low since you'll still get a failure notification on the next dependabot run, and uptime isn't super important. I expect its unlikely we'd get enough value to justify another dependency.  Maybe dependabot will expose their schema eventually (I think Actions is considering that option based on some conversations I had at All Things Open); at that point it might be more worthwhile.

**Pull request merged**
